pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'master', url: 'https://github.com/pratikshalavand98/flask-student-registration-jenkins.git'
            }
        }

        stage('Setup Environment') {
            steps {
                bat 'python -m pip install --upgrade pip'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat 'pip install flask mysql-connector-python'
            }
        }

        stage('Run Application') {
            steps {
                bat 'python app.py'
            }
        }
    }

    post {
        success {
            echo 'Build Successful 🎉'
        }
        failure {
            echo 'Build Failed ❌ Check logs'
        }
    }
}
