pipeline {
    agent any

    environment {
        GIT_REPO = 'https://github.com/pratikshalavand98/flask-student-registration-jenkins.git'
        BRANCH = 'master'
    }

    stages {

        stage('Checkout Code') {
            steps {
                echo 'Cloning GitHub Repository...'
                git branch: "${BRANCH}", url: "${GIT_REPO}"
            }
        }

        stage('Verify Files') {
            steps {
                echo 'Listing project files...'
                sh 'ls -la'
            }
        }

        stage('Setup Python Environment') {
            steps {
                echo 'Installing dependencies...'
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                '''
            }
        }

        stage('Run Tests') {
            steps {
                echo 'Running basic tests...'
                sh '''
                    . venv/bin/activate
                    python -m pytest || true
                '''
            }
        }

        stage('Run Application') {
            steps {
                echo 'Starting Flask App (Test Run Only)...'
                sh '''
                    . venv/bin/activate
                    export FLASK_APP=app.py
                    nohup python app.py &
                '''
            }
        }
    }

    post {
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed. Check logs.'
        }
    }
}
