pipeline {
    agent any

    stages {

        stage('Clone Code') {
            steps {
                git branch: 'master', url: 'https://github.com/pratikshalavand98/flask-student-registration-jenkins.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat 'pip install flask mysql-connector-python'
            }
        }

        stage('Run App') {
            steps {
                bat 'python app.py'
            }
        }
    }
}
